import recipe1 from '../../assets/images/recipe1.jpg';

const mockData = [
	{
		recipeID: 1,
		userID: 'user1',
		userName: 'User 1',
		title: 'Pasta Carbonara',
		description: 'Classic Italian pasta dish with eggs, cheese, and bacon.',
		ingredients: ['Spaghetti', 'Eggs', 'Parmesan cheese', 'Bacon', 'Black pepper'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 2,
		userID: 'user2',
		userName: 'User 2',
		title: 'Chicken Curry',
		description: 'Delicious Indian curry with tender chicken and aromatic spices.',
		ingredients: ['Chicken', 'Onion', 'Tomato', 'Coconut milk', 'Curry powder'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 3,
		userID: 'user3',
		userName: 'User 3',
		title: 'Caprese Salad',
		description: 'Simple and refreshing salad with tomatoes, mozzarella, and basil.',
		ingredients: [
			'Tomatoes',
			'Fresh mozzarella',
			'Basil leaves',
			'Olive oil',
			'Balsamic vinegar',
		],
		image: recipe1,
		category: 'Salads',
	},
	{
		recipeID: 4,
		userID: 'user4',
		userName: 'User 4',
		title: 'Spaghetti Bolognese',
		description: 'Classic Italian pasta dish with meaty tomato sauce.',
		ingredients: ['Spaghetti', 'Ground beef', 'Tomato sauce', 'Onion', 'Garlic'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 5,
		userID: 'user5',
		userName: 'User 5',
		title: 'Chocolate Cake',
		description: 'Rich and moist chocolate cake with chocolate frosting.',
		ingredients: ['All-purpose flour', 'Sugar', 'Cocoa powder', 'Butter', 'Eggs'],
		image: recipe1,
		category: 'Desserts',
	},
	{
		recipeID: 6,
		userID: 'user6',
		userName: 'User 6',
		title: 'Mushroom Risotto',
		description: 'Creamy Italian rice dish cooked with mushrooms and parmesan cheese.',
		ingredients: ['Arborio rice', 'Mushrooms', 'Chicken broth', 'Parmesan cheese', 'Onion'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 7,
		userID: 'user7',
		userName: 'User 7',
		title: 'Vegetable Soup',
		description: 'Hearty soup made with a variety of fresh vegetables and vegetable broth.',
		ingredients: ['Carrots', 'Potatoes', 'Celery', 'Onion', 'Vegetable broth'],
		image: recipe1,
		category: 'Soups',
	},
	{
		recipeID: 8,
		userID: 'user8',
		userName: 'User 8',
		title: 'Tiramisu',
		description:
			'Classic Italian dessert made with coffee-soaked ladyfingers and mascarpone cream.',
		ingredients: ['Ladyfingers', 'Mascarpone cheese', 'Eggs', 'Sugar', 'Coffee'],
		image: recipe1,
		category: 'Desserts',
	},
	{
		recipeID: 9,
		userID: 'user9',
		userName: 'User 9',
		title: 'Caesar Salad',
		description:
			'Classic salad with romaine lettuce, croutons, parmesan cheese, and Caesar dressing.',
		ingredients: [
			'Romaine lettuce',
			'Croutons',
			'Parmesan cheese',
			'Caesar dressing',
			'Anchovies',
		],
		image: recipe1,
		category: 'Salads',
	},
	{
		recipeID: 10,
		userID: 'user10',
		userName: 'User 10',
		title: 'Beef Stroganoff',
		description: 'Comforting Russian dish with tender beef in a creamy mushroom sauce.',
		ingredients: ['Beef', 'Mushrooms', 'Sour cream', 'Onion', 'Paprika'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 11,
		userID: 'user11',
		userName: 'User 11',
		title: 'Greek Salad',
		description:
			'Refreshing salad with tomatoes, cucumbers, olives, feta cheese, and Greek dressing.',
		ingredients: ['Tomatoes', 'Cucumbers', 'Olives', 'Feta cheese', 'Olive oil'],
		image: recipe1,
		category: 'Salads',
	},
	{
		recipeID: 12,
		userID: 'user12',
		userName: 'User 12',
		title: 'Lemon Chicken',
		description: 'Tender chicken breasts cooked in a tangy lemon sauce with garlic and herbs.',
		ingredients: ['Chicken breasts', 'Lemon', 'Garlic', 'Chicken broth', 'Thyme'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 13,
		userID: 'user13',
		userName: 'User 13',
		title: 'Ratatouille',
		description:
			'Classic French vegetable stew made with eggplant, zucchini, bell peppers, and tomatoes.',
		ingredients: ['Eggplant', 'Zucchini', 'Bell peppers', 'Tomatoes', 'Garlic'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 14,
		userID: 'user14',
		userName: 'User 14',
		title: 'Apple Pie',
		description: 'Classic American dessert made with sweet apples and a flaky pie crust.',
		ingredients: ['Apples', 'Sugar', 'Cinnamon', 'Flour', 'Butter'],
		image: recipe1,
		category: 'Desserts',
	},
	{
		recipeID: 15,
		userID: 'user15',
		userName: 'User 15',
		title: 'Shakshuka',
		description:
			'Middle Eastern dish of poached eggs in a spicy tomato sauce with peppers and onions.',
		ingredients: ['Eggs', 'Tomatoes', 'Bell peppers', 'Onion', 'Cumin'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 16,
		userID: 'user16',
		userName: 'User 16',
		title: 'Pumpkin Soup',
		description: 'Creamy soup made with fresh pumpkin, onions, garlic, and vegetable broth.',
		ingredients: ['Pumpkin', 'Onion', 'Garlic', 'Vegetable broth', 'Cream'],
		image: recipe1,
		category: 'Soups',
	},
	{
		recipeID: 17,
		userID: 'user17',
		userName: 'User 17',
		title: 'Tofu Stir-Fry',
		description: 'Healthy and flavorful stir-fry made with tofu, vegetables, and soy sauce.',
		ingredients: ['Tofu', 'Broccoli', 'Carrots', 'Soy sauce', 'Ginger'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 18,
		userID: 'user18',
		userName: 'User 18',
		title: 'Banana Bread',
		description: 'Moist and delicious banana bread made with ripe bananas and walnuts.',
		ingredients: ['Bananas', 'Flour', 'Sugar', 'Walnuts', 'Butter'],
		image: recipe1,
		category: 'Breads',
	},
	{
		recipeID: 19,
		userID: 'user19',
		userName: 'User 19',
		title: 'Quinoa Salad',
		description:
			'Healthy and nutritious salad made with quinoa, vegetables, and a lemon vinaigrette.',
		ingredients: ['Quinoa', 'Cucumber', 'Tomatoes', 'Lemon juice', 'Olive oil'],
		image: recipe1,
		category: 'Salads',
	},
	{
		recipeID: 20,
		userID: 'user20',
		userName: 'User 20',
		title: 'Beef Tacos',
		description: 'Mexican street food classic with seasoned beef, salsa, and guacamole.',
		ingredients: ['Ground beef', 'Taco shells', 'Tomatoes', 'Lettuce', 'Cheddar cheese'],
		image: recipe1,
		category: 'Main Course',
	},
	{
		recipeID: 21,
		userID: 'user21',
		userName: 'User 21',
		title: 'Pancakes',
		description: 'Fluffy and delicious pancakes served with maple syrup and butter.',
		ingredients: ['Flour', 'Milk', 'Eggs', 'Butter', 'Maple syrup'],
		image: recipe1,
		category: 'Breakfast',
	},
	{
		recipeID: 22,
		userID: 'user22',
		userName: 'User 22',
		title: 'Mango Smoothie',
		description: 'Refreshing smoothie made with fresh mango, yogurt, and honey.',
		ingredients: ['Mango', 'Yogurt', 'Honey', 'Ice cubes', 'Milk'],
		image: recipe1,
		category: 'Beverages',
	},
];

export default mockData;
